# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8711cba688d40ac1844d47c627177dc5"
name = "ys-image-optimizer"
handle = "ys-image-optimizer"
application_url = "https://civilian-ballet-allan-chancellor.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_files, write_files"

[auth]
redirect_urls = [
  "https://civilian-ballet-allan-chancellor.trycloudflare.com/auth/callback",
  "https://civilian-ballet-allan-chancellor.trycloudflare.com/auth/shopify/callback",
  "https://civilian-ballet-allan-chancellor.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
